parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
env:
  browser: true
  node: true
  es6: true
plugins:
  - prettier
  - react
  - react-native
  - import
  - flowtype
extends:
  - plugin:react/recommended
  - plugin:import/errors
  - prettier
  - prettier/flowtype
  - prettier/react
rules:
  # rules
  quotes: ["error", "single"]
  semi: ["error", "never"]
  indent: [2, 2, { "SwitchCase": 1 }]
  comma-dangle: ["error", "always-multiline"]
  prefer-const: 2
  no-var: 2
  no-unused-vars:
    - 2
    - argsIgnorePattern: ^_
  no-multiple-empty-lines:
    - 2
    - max: 1
  no-cond-assign: 2
  # react
  react/prop-types: 0
  react/no-string-refs: 0
  react/prefer-stateless-function: [1, { "ignorePureComponents": true }]
  react/no-unused-state: 2
  # react-native
  react-native/no-unused-styles: 2
  react-native/no-inline-styles: 1
  # import
  import/newline-after-import: 2
  import/imports-first: 2
  import/default: 0
  # import/prefer-default-export: 0
  import/no-dynamic-require: 2
  import/no-extraneous-dependencies: 2
  import/no-mutable-exports: 2
  import/no-commonjs: 2
